package org.infinite.db.dto;

// Generated 8-lug-2009 10.08.07 by Hibernate Tools 3.2.4.CR1

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private Integer id;
	private String name;
	private String description;
	private Integer world;
	private Integer nx;
	private Integer ny;

	public Area() {
	}

	public Area(String name, String description, Integer world, Integer nx,
			Integer ny) {
		this.name = name;
		this.description = description;
		this.world = world;
		this.nx = nx;
		this.ny = ny;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getWorld() {
		return this.world;
	}

	public void setWorld(Integer world) {
		this.world = world;
	}

	public Integer getNx() {
		return this.nx;
	}

	public void setNx(Integer nx) {
		this.nx = nx;
	}

	public Integer getNy() {
		return this.ny;
	}

	public void setNy(Integer ny) {
		this.ny = ny;
	}

}
