package org.infinite.db.dto;

// Generated 8-lug-2009 10.08.07 by Hibernate Tools 3.2.4.CR1

/**
 * PlayerOwnQuest generated by hbm2java
 */
public class PlayerOwnQuest implements java.io.Serializable {

	private Integer id;
	private Player player;
	private Quest quest;
	private Integer status;
	private Integer ncompleted;

	public PlayerOwnQuest() {
	}

	public PlayerOwnQuest(Player player, Quest quest, Integer status,
			Integer ncompleted) {
		this.player = player;
		this.quest = quest;
		this.status = status;
		this.ncompleted = ncompleted;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Player getPlayer() {
		return this.player;
	}

	public void setPlayer(Player player) {
		this.player = player;
	}

	public Quest getQuest() {
		return this.quest;
	}

	public void setQuest(Quest quest) {
		this.quest = quest;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Integer getNcompleted() {
		return this.ncompleted;
	}

	public void setNcompleted(Integer ncompleted) {
		this.ncompleted = ncompleted;
	}

}
