package org.infinite.db.dto;

import java.util.HashSet;
import java.util.Set;

/**
 * Quest generated by hbm2java
 */
public class Quest implements java.io.Serializable {

	
	private static final long serialVersionUID = -4562364153227041843L;
	private Integer id;
	private Integer goalItem;
	private Integer grantItem;
	private String name;
	private String descrPending;
	private String descrExecuted;
	private String descrCompleted;
	private Integer reqLev;
	private Integer reqQuest;
	private Integer goalItemN;
	private boolean repeats;
	private float grantGold;
	private Integer grantXp;
	private Set<PlayerOwnQuest> playerOwnQuests = new HashSet<PlayerOwnQuest>(0);

	public Quest() {
	}

	public Quest(Integer goalItem, Integer grantItem, String name,
			String descrPending, String descrExecuted, String descrCompleted,
			Integer reqLev, Integer goalItemN, boolean repeats, float grantGold,
			Integer grantXp) {
		this.goalItem = goalItem;
		this.grantItem = grantItem;
		this.name = name;
		this.descrPending = descrPending;
		this.descrExecuted = descrExecuted;
		this.descrCompleted = descrCompleted;
		this.reqLev = reqLev;
		this.goalItemN = goalItemN;
		this.repeats = repeats;
		this.grantGold = grantGold;
		this.grantXp = grantXp;
	}

	public Quest(Integer goalItem, Integer grantItem, String name,
			String descrPending, String descrExecuted, String descrCompleted,
			Integer reqLev, Integer reqQuest, Integer goalItemN,
			boolean repeats, float grantGold, Integer grantXp,
			Set<PlayerOwnQuest> playerOwnQuests, Set<Npc> npcs) {
		this.goalItem = goalItem;
		this.grantItem = grantItem;
		this.name = name;
		this.descrPending = descrPending;
		this.descrExecuted = descrExecuted;
		this.descrCompleted = descrCompleted;
		this.reqLev = reqLev;
		this.reqQuest = reqQuest;
		this.goalItemN = goalItemN;
		this.repeats = repeats;
		this.grantGold = grantGold;
		this.grantXp = grantXp;
		this.playerOwnQuests = playerOwnQuests;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getGoalItem() {
		return this.goalItem;
	}

	public void setGoalItem(Integer goalItem) {
		this.goalItem = goalItem;
	}

	public Integer getGrantItem() {
		return this.grantItem;
	}

	public void setGrantItem(Integer grantItem) {
		this.grantItem = grantItem;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescrPending() {
		return this.descrPending;
	}

	public void setDescrPending(String descrPending) {
		this.descrPending = descrPending;
	}

	public String getDescrExecuted() {
		return this.descrExecuted;
	}

	public void setDescrExecuted(String descrExecuted) {
		this.descrExecuted = descrExecuted;
	}

	public String getDescrCompleted() {
		return this.descrCompleted;
	}

	public void setDescrCompleted(String descrCompleted) {
		this.descrCompleted = descrCompleted;
	}

	public Integer getReqLev() {
		return this.reqLev;
	}

	public void setReqLev(Integer reqLev) {
		this.reqLev = reqLev;
	}

	public Integer getReqQuest() {
		return this.reqQuest;
	}

	public void setReqQuest(Integer reqQuest) {
		this.reqQuest = reqQuest;
	}

	public Integer getGoalItemN() {
		return this.goalItemN;
	}

	public void setGoalItemN(Integer goalItemN) {
		this.goalItemN = goalItemN;
	}

	public boolean isRepeats() {
		return this.repeats;
	}

	public void setRepeats(boolean repeats) {
		this.repeats = repeats;
	}

	public float getGrantGold() {
		return this.grantGold;
	}

	public void setGrantGold(float grantGold) {
		this.grantGold = grantGold;
	}

	public Integer getGrantXp() {
		return this.grantXp;
	}

	public void setGrantXp(Integer grantXp) {
		this.grantXp = grantXp;
	}

	public Set<PlayerOwnQuest> getPlayerOwnQuests() {
		return this.playerOwnQuests;
	}

	public void setPlayerOwnQuests(Set<PlayerOwnQuest> playerOwnQuests) {
		this.playerOwnQuests = playerOwnQuests;
	}

}
