package org.infinite.db.dto;

// Generated 8-lug-2009 10.08.07 by Hibernate Tools 3.2.4.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Quest generated by hbm2java
 */
public class Quest implements java.io.Serializable {

	private static final long serialVersionUID = 6993854633291815743L;
	
	private Integer id;
	private Item itemByGoalItem;
	private Item itemByGrantItem;
	private Quest quest;
	private String name;
	private String descrPending;
	private String descrExecuted;
	private Integer reqLev;
	private Integer goalItemN;
	private boolean repeat;
	private float grantGold;
	private Integer grantXp;
	private Set<PlayerOwnQuest> playerOwnQuests = new HashSet<PlayerOwnQuest>(0);
	private Set<Quest> quests = new HashSet<Quest>(0);

	public Quest() {
	}

	public Quest(Item itemByGoalItem, Item itemByGrantItem, Quest quest,
			String name, String descrPending, String descrExecuted,
			Integer reqLev, Integer goalItemN, boolean repeat, float grantGold,
			Integer grantXp) {
		this.itemByGoalItem = itemByGoalItem;
		this.itemByGrantItem = itemByGrantItem;
		this.quest = quest;
		this.name = name;
		this.descrPending = descrPending;
		this.descrExecuted = descrExecuted;
		this.reqLev = reqLev;
		this.goalItemN = goalItemN;
		this.repeat = repeat;
		this.grantGold = grantGold;
		this.grantXp = grantXp;
	}

	public Quest(Item itemByGoalItem, Item itemByGrantItem, Quest quest,
			String name, String descrPending, String descrExecuted,
			Integer reqLev, Integer goalItemN, boolean repeat, float grantGold,
			Integer grantXp, Set<PlayerOwnQuest> playerOwnQuests,
			Set<Quest> quests) {
		this.itemByGoalItem = itemByGoalItem;
		this.itemByGrantItem = itemByGrantItem;
		this.quest = quest;
		this.name = name;
		this.descrPending = descrPending;
		this.descrExecuted = descrExecuted;
		this.reqLev = reqLev;
		this.goalItemN = goalItemN;
		this.repeat = repeat;
		this.grantGold = grantGold;
		this.grantXp = grantXp;
		this.playerOwnQuests = playerOwnQuests;
		this.quests = quests;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Item getItemByGoalItem() {
		return this.itemByGoalItem;
	}

	public void setItemByGoalItem(Item itemByGoalItem) {
		this.itemByGoalItem = itemByGoalItem;
	}

	public Item getItemByGrantItem() {
		return this.itemByGrantItem;
	}

	public void setItemByGrantItem(Item itemByGrantItem) {
		this.itemByGrantItem = itemByGrantItem;
	}

	public Quest getQuest() {
		return this.quest;
	}

	public void setQuest(Quest quest) {
		this.quest = quest;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescrPending() {
		return this.descrPending;
	}

	public void setDescrPending(String descrPending) {
		this.descrPending = descrPending;
	}

	public String getDescrExecuted() {
		return this.descrExecuted;
	}

	public void setDescrExecuted(String descrExecuted) {
		this.descrExecuted = descrExecuted;
	}

	public Integer getReqLev() {
		return this.reqLev;
	}

	public void setReqLev(Integer reqLev) {
		this.reqLev = reqLev;
	}

	public Integer getGoalItemN() {
		return this.goalItemN;
	}

	public void setGoalItemN(Integer goalItemN) {
		this.goalItemN = goalItemN;
	}

	public boolean isRepeat() {
		return this.repeat;
	}

	public void setRepeat(boolean repeat) {
		this.repeat = repeat;
	}

	public float getGrantGold() {
		return this.grantGold;
	}

	public void setGrantGold(float grantGold) {
		this.grantGold = grantGold;
	}

	public Integer getGrantXp() {
		return this.grantXp;
	}

	public void setGrantXp(Integer grantXp) {
		this.grantXp = grantXp;
	}

	public Set<PlayerOwnQuest> getPlayerOwnQuests() {
		return this.playerOwnQuests;
	}

	public void setPlayerOwnQuests(Set<PlayerOwnQuest> playerOwnQuests) {
		this.playerOwnQuests = playerOwnQuests;
	}

	public Set<Quest> getQuests() {
		return this.quests;
	}

	public void setQuests(Set<Quest> quests) {
		this.quests = quests;
	}

}
